export const functions = [
  { id: "aizawa", name: "Aizawa", tag: "Aiz" },
  { id: "arneodo", name: "Arneodo", tag: "Arn" },
  { id: "chen", name: "Chen", tag: "Che" },
  { id: "dadras", name: "Dadras", tag: "Dad" },
  { id: "dequan", name: "Dequan", tag: "Deq" },
  { id: "fourwing", name: "Four-Wing", tag: "4W" },
  { id: "halvorsen", name: "Halvorsen", tag: "Hal" },
  { id: "lorenz", name: "Lorenz", tag: "Lor" },
  { id: "lorenz83", name: "Lorenz83", tag: "L83" },
  { id: "lorenzMod2", name: "Lorenz Mod 2", tag: "LM2" },
  { id: "rabin", name: "Rabinovich-Fabrikant", tag: "Rab" },
  { id: "rossler", name: "Rössler", tag: "Ros" },
  { id: "sprott", name: "Sprott", tag: "Spr" },
  { id: "thomas", name: "Thomas", tag: "Tho" },
  {
    id: "threeScroll1",
    name: "Three-Scroll Unified Chaotic System v1",
    tag: "TS1",
  },
  {
    id: "threeScroll2",
    name: "Three-Scroll Unified Chaotic System v2",
    tag: "TS2",
  },
];
